name: Test and Deploy Allure to Pages

on:
  push:
    branches:
      - main
      - tests/dev
  workflow_dispatch:
    inputs:
      update_snapshots:
        description: "Update visual snapshots (toHaveScreenshot baselines)"
        type: boolean
        default: false
        required: false
      run_visual:
        description: "Include visual tests (@visual) without updating snapshots"
        type: boolean
        default: false
        required: false

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-and-build:
    name: Run Playwright and build Allure
    runs-on: ubuntu-latest
    env:
      UPDATE_SNAPSHOTS: ${{ inputs.update_snapshots || 'false' }}
      RUN_VISUAL: ${{ inputs.run_visual || 'false' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --no-audit --no-fund

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run tests
        run: |
          if [ "${UPDATE_SNAPSHOTS}" = "true" ]; then
            echo "Updating visual snapshots...";
            npx playwright test --grep @visual --update-snapshots;
          elif [ "${RUN_VISUAL}" = "true" ]; then
            echo "Running visual tests without updating snapshots...";
            if ls tests/*-snapshots/*.png 1> /dev/null 2>&1; then
              npx playwright test --grep @visual;
            else
              echo "No visual baselines found. Bootstrapping snapshots for this run (no commit).";
              npx playwright test --grep @visual --update-snapshots;
            fi
          else
            npx playwright test --grep-invert @visual;
          fi

      - name: Generate Allure static site
        run: |
          npm run allure:generate
          touch ./docs/.nojekyll

      - name: Commit updated visual snapshots
        if: ${{ inputs.update_snapshots == true && github.ref == 'refs/heads/main' }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          files=$(find tests -type f -path '*-snapshots/*.png')
          if [ -n "${files}" ]; then
            echo "Staging snapshot files:" ${files}
            git add ${files}
            git commit -m "chore: update visual snapshots" || echo "No snapshot changes"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
          else
            echo "No snapshot files to commit"
          fi

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  deploy:
    needs: test-and-build
    if: ${{ github.ref == 'refs/heads/main' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


