name: Playwright Tests + Allure Report

on:
  workflow_dispatch:

permissions:
  contents: write  # ← даём право на запись

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install --no-audit --no-fund

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Generate Allure Report
        run: |
          npm install -g allure-commandline
          allure generate allure-results -o allure-report --clean

      - name: Prepare Allure Report for GitHub Pages
        run: |
          mkdir -p docs
          cp -r allure-report/* docs/
          touch docs/.nojekyll

      - name: Commit and Push Allure Report
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add docs/
          git commit -m "Update Allure report" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/